model:
  backbone: resnet18
  pretrained: true
  num_classes: 28  # عدد الحروف العربية
  image_size: [224, 224]

training:
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 5
  validation_split: 0.2
  
data_augmentation:
  rotation_range: 15
  width_shift_range: 0.1
  height_shift_range: 0.1
  zoom_range: 0.1
  brightness_range: [0.8, 1.2]
  
preprocessing:
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  denoise_strength: 10
  threshold_method: "adaptive"
  threshold_block_size: 11
  threshold_C: 2
